package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.PlanPojo;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class DeletePlanTest {
    private static AccountTokenPojo adminToken;

    private static PlanPojo planPojo;

    @BeforeClass
    public static void before() {
        adminToken = new RestClient().authenticate("admin", "setup");
        planPojo = new RestClient().createAutoGeneratedPlan(adminToken);
    }

    @Test(description = "Delete plan.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Delete plan feature.")
    public void deletePlanTest() {
        new RestClient().deletePlan(adminToken, planPojo.id);
    }


    @Test(description = "Get plans after delete.", dependsOnMethods = "deletePlanTest")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Delete plan feature.")
    public void getPlansAfterDeleteTest() {
        Assert.assertTrue(new RestClient().getPlans(adminToken).stream().noneMatch(plan -> planPojo.equals(plan)));
    }
}
